<store-strings-setter
        strings="{{ json_encode([
                        'key' => 'review-for-payment',
                        'values' => [
                                'contentHeader' => trans('strings.view_reviewForPayment_header'),
                                'tableHeaderOptionName' => trans('strings.view_reviewForPayment_table_option_name'),
                                'tableHeaderOptionQuantity' => trans('strings.view_reviewForPayment_table_option_quantity'),
                                'tableHeaderOptionCost' => trans('strings.view_reviewForPayment_table_option_cost'),
                                'tableTotalExclVat' => trans('strings.view_reviewForPayment_table_total_excl_vat'),
                                'tableTotalVat' => trans('strings.view_reviewForPayment_table_vat'),
                                'tableTotalInclVat' => trans('strings.view_reviewForPayment_table_total_incl_vat'),
                                'toggleCgvLabel' => trans('strings.view_reviewForPayment_cgv', ['link' => route('cgv')]),
                                'lockInfoHeader' => trans('strings.view_reviewForPayment_lock_info_header'),
                                'lockInfoContent' => trans('strings.view_reviewForPayment_lock_info_content'),
                                'paypalBtnTitle' => trans('strings.view_reviewForPayment_paypal_title'),
                                'dividerChoiceLabel' => trans('strings.divider_payment'),
                                'paymentCardTypeLabel' => trans('strings.payment_card_type_label'),
                                'paymentCardNameLabel' => trans('strings.payment_card_name_label'),
                                'paymentCardNameError' => trans('strings.request_input_regex_name', ['name' => trans('strings.payment_card_name_label')]),
                                'paymentCardNumberLabel' => trans('strings.payment_card_number_label'),
                                'paymentCardNumberError' => trans('strings.payment_card_number_error'),
                                'paymentCardNumberPlaceholder' => trans('strings.payment_card_number_placeholder'),
                                'paymentCardCvcLabel' => trans('strings.payment_card_cvc_label'),
                                'paymentCardCvcError' => trans('strings.request_input_generic_error', ['name' => trans('strings.payment_card_cvc_label')]),
                                'paymentCardExpirationLabel' => trans('strings.payment_card_expiration_label'),
                                'paymentCardExpirationMonthPlaceholder' => trans('strings.payment_card_expiration_month_placeholder'),
                                'paymentCardExpirationYearPlaceholder' => trans('strings.payment_card_expiration_year_placeholder'),
                                'paymentCardYearError' => trans('strings.request_input_generic_error', ['name' => trans('strings.payment_card_expiration_year_placeholder')]),
                                'january' => trans('strings.january'),
                                'february' => trans('strings.february'),
                                'march' => trans('strings.march'),
                                'april' => trans('strings.april'),
                                'may' => trans('strings.may'),
                                'june' => trans('strings.june'),
                                'july' => trans('strings.july'),
                                'august' => trans('strings.august'),
                                'september' => trans('strings.september'),
                                'october' => trans('strings.october'),
                                'november' => trans('strings.november'),
                                'december' => trans('strings.december'),
                                'paymentTempoMessage' => trans('strings.view_reviewForPayment_tempo'),
                                'stepOneTitle' => isset($title) ?  $title : trans('strings.view_advert_steps_1_title'),
                                'stepTwoTitle' => trans('strings.view_advert_steps_2_title'),
                                'stepThreeTitle' => trans('strings.view_advert_steps_3_title'),
                                'stepThreeTitlePost' => trans('strings.view_advert_steps_3_title_post'),
                                'stepOneDescription' => isset($title) ?  '' : trans('strings.view_advert_steps_1_description'),
                                'stepTwoDescription' => trans('strings.view_advert_steps_2_description'),
                                'stepThreeDescription' => trans('strings.view_advert_steps_3_description'),
                        ]
                ])}}"
></store-strings-setter>